version: 2
jobs:
  test:
    docker: 
      - image: circleci/node:9.5.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build-prod-react-app:
    docker:
      - image: circleci/node:9.5.0
    steps:
      - checkout
      - run: npm install --prefix client 
      - run: npm run build --prefix client
      - persist_to_workspace:
          root: client/build
  deploy:
    docker:
      - image:  google/cloud-sdk
    steps:
      - checkout
# retrieve previously built production react app
      - run: mkdir client/build
      - attach_workspace:
          at: client/build
# write production environment variables to app.yaml
      - run: printf "env_variables:\n" >> app.yaml
      - run: printf "  GOOGLE_CLIENT_ID:" >> app.yaml
      - run: printf " \"$GOOGLE_CLIENT_ID\"\n" >> app.yaml
      - run: printf "  GOOGLE_CLIENT_SECRET:" >> app.yaml
      - run: printf " \"$GOOGLE_CLIENT_SECRET\"\n" >> app.yaml
      - run: printf "  MONGO_URI:" >> app.yaml
      - run: printf " \"$MONGO_URI\"\n" >> app.yaml
      - run: printf "  COOKIE_KEY:" >> app.yaml
      - run: printf " \"$COOKIE_KEY\"\n" >> app.yaml
      - run: printf "  REDIRECT_DOMAIN:" >> app.yaml
      - run: printf " \"$REDIRECT_DOMAIN\"\n" >> app.yaml
      - run: printf "  SENDGRID_KEY:" >> app.yaml
      - run: printf " \"$SENDGRID_KEY\"\n" >> app.yaml
# deploy to google app engine
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garb > ${HOME}/gcloud-service-key.json
      - run: apt-get install google-cloud-sdk
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud config set project melanjj-prod
      - run: gcloud app deploy
workflows:
  version: 2
  test-and-deploy: 
    jobs:
      - test
      - build-prod-react-app
      - deploy:
          requires:
            - test
            - build-prod-react-app
          filters:
            branches:
              only:
                - master
          