version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0
    steps:
      - checkout
      - run:
          name: decode-gcloud-key
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garb
      - run: sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
      - run: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud config set project melanjj-prod

          