version: 2
jobs:
  test:
    docker: 
      - image: circleci/node:9.5.0
    steps:
      - run: npm run test
  deploy:
    docker:
      - image:  google/cloud-sdk
    steps:
      - checkout
      - run: printf "env_variables:\n" >> app.yaml
      - run: printf "  GOOGLE_CLIENT_ID:" >> app.yaml
      - run: printf " \"$GOOGLE_CLIENT_ID\"\n" >> app.yaml
      - run: printf "  GOOGLE_CLIENT_SECRET:" >> app.yaml
      - run: printf " \"$GOOGLE_CLIENT_SECRET\"\n" >> app.yaml
      - run: printf "  MONGO_URI:" >> app.yaml
      - run: printf " \"$MONGO_URI\"\n" >> app.yaml
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garb > ${HOME}/gcloud-service-key.json
      - run: apt-get install google-cloud-sdk
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud config set project melanjj-prod
      - run: gcloud app deploy
workflows:
  version: 2
  test-and-deploy: 
    jobs:
      - test
      - deploy:
          requires:
            - test
          