version: 2
jobs:
  build:
    docker:
      - image:  google/cloud-sdk
    steps:
      - checkout
      - run:
          name: decode-gcloud-key
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garb
      - run: gcloud --quiet components update
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud config set project melanjj-prod

          