version: 2
jobs:
  build:
    docker:
      - image:  google/cloud-sdk
    steps:
      - checkout
      - run: echo "env_variables:" >> app.yaml
      - run: echo "  GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID" >> app.yaml
      - run: echo "env_variables:" >> app.yaml
      # - run: echo "env_variables:" >> app.yaml
      # - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garb > ${HOME}/gcloud-service-key.json
      # - run: apt-get install google-cloud-sdk
      # - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      # - run: gcloud config set project melanjj-prod
      # - run: gcloud app deploy

          