version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0
    steps:
      - checkout
      - run:
          name: decode-gcloud-key
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json

